from person import Person
import pandas as pd
import numpy as np
import time
from datetime import datetime
from time import mktime
import seaborn as sns
import matplotlib.pyplot as plt


def chat_fix(messages, timestamps):
    # Fixing the messages list from errors resulting from the multiline messages in the original file and creating a dates list
    for i in range(len(messages)):
        try:
            timestamps.append(time.strptime(messages[i].split('-')[0].split(',')[0] + messages[i].split('-')[0].split(',')[1], '%m/%d/%y %H:%M '))
        except:
            num = 1
            while True:
                if messages[i - num] != 'NaN':
                    messages[i - num] += (' ' + messages[i])
                    messages[i] = 'NaN'
                    break
                else:
                    num += 1


def remove_nan(messages):
    while True:
        try:
            messages.remove('NaN')
        except ValueError:
            break

# Reading from the file generated by WhatsApp
with open('WhatsApp Chat with Sara.txt', 'r') as chat:
    messages = chat.readlines()

people = []
names = []
person = []
timestamps = []
content = []
hours = []

day = []
month = []
year = []

chat_fix(messages, timestamps)

remove_nan(messages)

for message in messages:
    try:
        content.append(message.split('-')[1].split(':', maxsplit=1)[1].replace(' ', '', 1))
        person.append(message.split('-')[1].split(':', maxsplit=1)[0].replace(' ', '', 1))
    except:
        content.append(message.split('-')[1].replace(' ', '', 1))
        person.append('-')

for timestamp in timestamps:
    day.append(datetime.fromtimestamp(mktime(timestamp)).date().day)
    month.append(datetime.fromtimestamp(mktime(timestamp)).date().month)
    year.append(datetime.fromtimestamp(mktime(timestamp)).date().year)
    hours.append(datetime.fromtimestamp(mktime(timestamp)).time())

index = pd.MultiIndex.from_arrays([year, month, day, person], names=['Year', 'Month', 'Day', 'Person'])

chat_data = pd.DataFrame({'Time': hours, 'Content': content}, index=index)
#chat_data = pd.DataFrame(list(zip(dates, hours, content, person)), columns = ['Date', 'Time', 'Content', 'Person'])
chat_data.drop('-', level='Person', inplace=True)

# list of names of people in the conversation
names = set(person)
names.remove('-')

# TO DO
# maybe useful embark = pd.get_dummies(train['Embarked'], drop_first=True)
# saving text to file
# Explore plt.figure and how it can link to the seaborn plot
# Groupby can be done based on multiple columns df.groupby(['Day of Week', 'Hour']).count()
# improve printing of the most common words
# Graphs for monthly number of messages
# Monthly word averages
# Monthly word count
# Most common time of chatting, most common day, month as well

# This loop creates a person object for each person participating in the chat
for name in names:
    people.append(Person(name))

for person in people:
    person.count_messages(chat_data)
    person.most_common_words(chat_data)
    person.count_words(chat_data)
    person.calculate_average()
    person.count_media(chat_data)
    print(person)
'''
sns.set_style('darkgrid')
# plot of the amount of messages per month per person (here, specifically for 2019)
figure1, ax1 = plt.subplots()
sns.countplot(x=chat_data.loc[2019].index.get_level_values(level='Month'), data=chat_data.loc[2019], hue=chat_data.loc[2019].index.get_level_values(level='Person'))
figure1.savefig('MSGbyMonthPlot.png')

# plot of the amount of messages per day per person (here, specifically for 2019)
figure2, ax2 = plt.subplots()
sns.countplot(x=chat_data.loc[2019].index.get_level_values(level='Day'), data=chat_data.loc[2019], hue=chat_data.loc[2019].index.get_level_values(level='Person'))
figure2.savefig('MSGbyDayPlot.png')
'''
# plot of the amount of words per month per person (here, specifically for 2019)
# have the person class calculate these in the loop probably
words_sara = chat_data[chat_data['Content'] != '<Media omitted>\n'].xs('Sara', level='Person')['Content'].apply(lambda x: len(x.split()))
words_sum_sara = words_sara.groupby('Month').sum()
words_kamil = chat_data[chat_data['Content'] != '<Media omitted>\n'].xs('Kamil Kuźniak', level='Person')['Content'].apply(lambda x: len(x.split()))
words_sum_kamil = words_kamil.groupby('Month').sum()

figure3, ax3 = plt.subplots()
sns.barplot(x=words_sum_sara.index, y=words_sum_sara, alpha=0.5, color='red')
sns.barplot(x=words_sum_kamil.index, y=words_sum_kamil, alpha=0.5, color='blue')
figure3.savefig('WordsByMonthPlot.png')

plt.tight_layout()
plt.show()


# print('Kamil sent ' + str(round((1 - kamil_msg/sara_msg)*100)) + '% less messages than Sara')
# print('Kamil sent ' + str(round((1 - kamil_words / sara_words) * 100)) + '% less words than Sara')

# if __name__ == '__main__':
